[package]
name = "rustport"
version = "0.1.0"
edition = "2024"

[dependencies]
color-print = "0.3.7"
reqwest = {version = "0.13.1"}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
tokio = {version = "1.49.0", features = ["macros", "rt-multi-thread"]}
